DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS discount_card;

CREATE TABLE product
(
    id             INT GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1) PRIMARY KEY,
    product_name   TEXT    NOT NULL,
    price          FLOAT   NOT NULL,
    product_unit   TEXT    NOT NULL,
    is_promotional BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS discount_card;
CREATE TABLE discount_card
(
    id               INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1) PRIMARY KEY,
    discount_percent INT NOT NULL
);