DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS discount_card;
DROP TYPE IF EXISTS product_units;

CREATE TYPE product_units AS ENUM ('BULK','LIQUID','PIECE');

DROP TABLE IF EXISTS product;
CREATE TABLE product
(
    id             INT GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1) PRIMARY KEY,
    product_name   TEXT          NOT NULL,
    price          FLOAT         NOT NULL,
    product_unit   product_units NOT NULL,
    is_promotional BOOLEAN       NOT NULL
);

DROP TABLE IF EXISTS discount_card;
CREATE TABLE discount_card
(
    id               INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1) PRIMARY KEY,
    discount_percent INT NOT NULL
);